server:
  port: 8000
security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    username: home
    password: postgres
  application:
    name: user-service
