server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # config 정보를 저장할 위치
          uri: https://github.com/ShinMyeongJi/spring-cloud-with-msa.git
          basedir: config
          search-paths: dev, stg, prod


# 기본적인 acutator의 기본 엔드 포인트가 false로 설정되고, 아래 endpoint 정보에 의해 특정 정보만 true로 세팅한다.
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true